### ISSUE TITLE
Feature request - Add temp displacement as a entity for RCT

### ISSUE THREAD

**Issue by oyvindth** [karloygard/xcomfortd-go#24]
I have several RCT around the house, and when connecting them to HA they have 4 entities Temp/Moist/Battery/Signal.

When looking at the logs it also reports the temp displacement sett on the RTC (The adjustment wheel on the older thermostats) as "dropping wheel position on the ground: -3.0" is it possible to have this as a separate entity, so that this can be used to change the set temperature in HA for the specific zone?

**Comment by karloygard** [comment]
Adding the wheel position is trivial, it mostly depends how you want to expose it. I don't have a RCT, so I'm not sure what it reports, so for the time being, I just logged the wheel position and ignored it.

The wheel position could be exposed as a separate value (`offset`, maybe) or added to the reported temperature for simplicity. I don't know which is easier for you to deal with?

**Comment by oyvindth** [comment]
Reported as a separate value (offset is good) would be great in my use case. It would give me all the flexibility I need.


Kind Regards

Øyvind Thoresen


Fra: Karl Anders ***@***.***>
Sendt: mandag 19. juli 2021 kl. 22:24
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [karloygard/xcomfortd-go] Feature request - Add temp displacement as a entity for RCT (#24)


Adding the wheel position is trivial, it mostly depends how you want to expose it. I don't have a RCT, so I'm not sure what it reports, so for the time being, I just logged the wheel position and ignored it.

The wheel position could be exposed as a separate value (offset, maybe) or added to the reported temperature for simplicity. I don't know which is easier for you to deal with?

**Comment by oyvindth** [comment]
Updated to 0.36. the wheel position is no longer dropped on the floor in the xcomfort logs, but I see no entity displaying the value in the mqtt integration.

**Comment by karloygard** [comment]
I'm just experimenting at the moment.

**Comment by karloygard** [comment]
I just released 0.36.1, the temperature adjustment should hopefully show up now.

**Comment by oyvindth** [comment]
Working great.
