### ISSUE TITLE
Future request: Push buttons

### ISSUE THREAD

**Issue by DiseaseNO** [karloygard/xcomfortd-go#33]
Hi! Would it be possible for a future version to support the push buttons from xcomfort as well? The integrations is by the way working really good and stable.

**Comment by karloygard** [comment]
This should already work—you can trigger automations with the push buttons.

**Comment by DiseaseNO** [comment]
Thanks. I dont think I understand. 

I have multiple Xcomfort pust buttons in my house and I have connected these in MRF to connect to the 00/14 USB, and when I press, then I can see the buttons getting pressed in debug of the plugin. However I cannot see anything about the push buttons in MQTT.

**Comment by karloygard** [comment]
The way it's set up in HA today, pushbuttons can only be used for triggering automations. I have only tested this briefly a long time ago, but I believe it should be working fine still. See the image below:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/5375107/146695042-032c3ae3-c19c-423f-a04e-002513f8c83d.png">

**Comment by DiseaseNO** [comment]
Thank you! :)
