### ISSUE TITLE
HA complaining about temp sensors reporting with unsupported unit

### ISSUE THREAD

**Issue by E-K-I** [karloygard/xcomfortd-go#34]
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:269
Integration: Sensor (documentation, issues)
First occurred: 14:20:10 (4 occurrences)
Last logged: 15:00:10

sensor.temperature has unit C which is unsupported for device_class temperature
sensor.bad_vest_temperature has unit C which is unsupported for device_class temperature
sensor.temperature_adjustment_3 has unit C which is unsupported for device_class temperature
sensor.tekniskrom_temperatur has unit C which is unsupported for device_class temperature

**Comment by karloygard** [comment]
Yeah, that should probably be "°C". Will issue a fix.

**Comment by karloygard** [comment]
Resolved in 0.49.
