### ISSUE TITLE
Kommunikasjon fra analog converter

### ISSUE THREAD

**Issue by hlowe59** [karloygard/xcomfortd-go#39]
Lysstyring av markiser (lux-måling).
Jeg har en CAEE-02/01 som overfører signaler fra lux-sensorer (to separate målere gjennom to kanaler) for lysstyringen av markiser.
Jeg opplever at den bare gir signalstyrken inn i grensesnittet, er det noe sted jeg kan hente ut den aktuelle verdien?
Det fungerer greit inn i Sensio, og dermed via Xcomfort, men jeg klarer ikke å hente ut verdier annet enn signalstyrken.

Sliter litt her, men det er sikkert bare jeg som ikke forstår det hele....

**Comment by karloygard** [comment]
Du har rett, dette er ikke implementert ennå. Kan ta en titt.

**Comment by karloygard** [comment]
Tentativ fiks i 0.52. Se om endringen gjør noe fornuftig, jeg har ikke en CAEE-02/01 jeg kan teste med.

**Comment by hlowe59** [comment]
Heisann!
Nå ser jeg begge kanalene, blir spennende å se om verdiene endrer seg når lyset kommer. Det er jo lysmålere som er koblet til begge kanaler. Det er bek mørkt ute, klokken er 23.
Får en status etterhvert som lyset dukker opp i morgen, det er til og med meldt lettskyet og sol utover dagen!
Gir tilbakemelding da.

**Comment by hlowe59** [comment]
Virker fantastisk. Tusen takk!
![Skjermbilde 2022-02-04 090857](https://user-images.githubusercontent.com/96619545/152494100-c1d4f1d8-9f94-4d0f-9882-001f48b6bcef.jpg)

**Comment by karloygard** [comment]
Får dessverre ikke satt måleenhet, siden konfigurasjonsfilen ikke sier noe om hva det er som måles.

**Comment by hlowe59** [comment]
Alt OK. De måler lux - det er satt i MRF.
This is just perfect!!
