### ISSUE TITLE
Wall-switches not showing any entities

### ISSUE THREAD

**Issue by oyvindth** [karloygard/xcomfortd-go#41]
I have added a CTAA-02/04 Wall-button into my Home Assistant setup, but the only entities I get from the button is battery and signal strength. When I press the button, I can see the events "ON" "OFF" "UP Pressed" "UP Released" "Down Pressed" "Down Released" in the comfort logs, but I have no way of using that in my automations. The CTAA-02/04 seems to be correctly identified by the xComfort add-in, and all events are registred by the xComfort addin, but I see now way of using the info. Is there a possibility to att an entity to reflect the "ON" "OFF" "UP Pressed" "UP Released" "Down Pressed" "Down Released" state of the switch.

**Comment by karloygard** [comment]
Do you have some logs? This should work, but it's been a while since I tested it.

**Comment by karloygard** [comment]
You *should* be able to see something like this:

 <img width="690" alt="image" src="https://user-images.githubusercontent.com/5375107/162821143-b871b1ea-c7e6-4acb-8d46-d880ced9cbe0.png">

**Comment by oyvindth** [comment]
Thank you. This approach is working.
