### ISSUE TITLE
Dimmer does not turn on at last value from HA.

### ISSUE THREAD

**Issue by Futrax** [karloygard/xcomfortd-go#44]
When turning on a dimmer from Home assistant, the light turns on at max brightness every time.
The memory function when programming the dimmer to the communication stick.

**Comment by Knutingeev** [comment]
Has anything been done about this?
It would have been nice if you could switch on the dimmer in the old value

**Comment by karloygard** [comment]
Might be possible. I'm on vacation, but ping me in a week if you don't see any progress, I may have forgotten.

**Comment by Knutingeev** [comment]
Something new here?

**Comment by karloygard** [comment]
Tested just now and it seems to work out of the box? Am I misunderstanding something?

**Comment by Knutingeev** [comment]
If I go to a dimmer and turn it on and then adjust it to 40%.  If I turn it off, wait a few seconds before I turn it on again, it goes to 100%

**Comment by Knutingeev** [comment]
https://user-images.githubusercontent.com/96237669/196100764-67b817b8-b980-4049-b7bf-fd9b618500d4.MOV

**Comment by docstalek** [comment]
0.57 seems to have fixed this issue.
