### ISSUE TITLE
Drivers for EATON CKOZ-00/13

### ISSUE THREAD

**Issue by LuPe97** [karloygard/xcomfortd-go#6]
My devices dont recognize the stick and the software just tells me that no usb stick is found. 

Any tipps?

**Comment by karloygard** [comment]
This code supports the 00/14 device, not the 00/13. Confusing, I know. In practice, however, you will need both those devices in order to use this software.

**Comment by LuPe97** [comment]
Okay, thank you. 
Any Idea where to buy a 00/14 Stick?

**Comment by karloygard** [comment]
I have used these in the past: http://xcomfort-sklep.pl/index.php?id_product=140&controller=product&id_lang=1

**Comment by LuPe97** [comment]
Thank you!
