### ISSUE TITLE
MQTT Name changes in 2023:8

### ISSUE THREAD

**Issue by FSHelgeland** [karloygard/xcomfortd-go#62]
There have been some changes for naming mqtt-devices in the last update of the HA -core.  Causing for now only warnings, but I belive this will need a fix. Here is an example of a warning from the log:

"2023-08-02 23:27:16.735 WARNING (MainThread) [homeassistant.components.mqtt.mixins] MQTT device name is equal to entity name in your config {'device': {'identifiers': ['4315348'], 'manufacturer': 'Eaton', 'model': 'Motion Detector (CBMA-02/xx)', 'name': 'Bevegelse Entre (Kanal A)', 'via_device': 'CI Stick', 'connections': []}, 'device_class': <BinarySensorDeviceClass.MOTION: 'motion'>, 'name': 'Bevegelse Entre (Kanal A)', 'payload_off': 'switchOff', 'payload_on': 'switchOn', 'state_topic': 'xcomfort/44/event', 'unique_id': '4315348_ch0', 'qos': 0, 'force_update': False, 'encoding': 'utf-8', 'payload_not_available': 'offline', 'payload_available': 'online', 'enabled_by_default': True, 'availability_mode': 'latest'}, this is not expected. Please correct your configuration. The entity name will be set to `null`"

Hope there will be a fix for this soon. 

Br: Freddy

**Comment by karloygard** [comment]
I'll issue a fix when I find some time.

**Comment by karloygard** [comment]
I have attempted a fix in 5275306. It's not super obvious to me how naming should work in Home Assistant, but test it and see if it makes sense.

**Comment by FSHelgeland** [comment]
I installed as soon as you released it, so far it looks good.

**Comment by karloygard** [comment]
Will check tonight.

**Comment by FSHelgeland** [comment]
It seems like the switches listen for the topic in Node Red works as before, but the buttons directly integrated in Home Assistant in automations does not do anything. For me that is not a problem as I can trigger it from Node Red, that is meybee the best solution for me. But I do think you should have a look at it.

**Comment by karloygard** [comment]
It appears to work just fine here. I didn't touch that particular code, except renaming the discovery topic. The event topic itself was not renamed. Can you dig a bit and see what breaks your setup?

**Comment by karloygard** [comment]
Hah, that's no good. I'll extend the regex a bit.

**Comment by FSHelgeland** [comment]
Sov 1 Baddør ble til R, nå heter den Sov 1 Bad. Skal sjekke om jeg kan få bryterne til å trigge en automasjon.

**Comment by FSHelgeland** [comment]
I dont know what happened, but it works know. Maybe it was on the naming bit? I have removed everything with an .æøå in the names. Restarted the add on, restarted the mqtt broker and now it works fine.

**Comment by FSHelgeland** [comment]
I just noticed I have a lot of switches with the letter Ø in and also some with . I havent changed them, så I get a warning that they are missing. I think I wait and see if you manage to fix it before renaming them all, as I have multiple automations with those.

**Comment by karloygard** [comment]
Confirm that I see the issue. Fix forthcoming.

**Comment by FSHelgeland** [comment]
We do not have bad weather up in north, the summer seems to never end.

**Comment by FSHelgeland** [comment]
But I cant find any update though

**Comment by FSHelgeland** [comment]
After a restart it popped up, installing now.

**Comment by ChristopherSkarsethstuen** [comment]
Names are working now, but I still can't get any pushbuttons to trigger automations

**Comment by karloygard** [comment]
Can you try to figure out what has broken your setup?

**Comment by ChristopherSkarsethstuen** [comment]
Working now. Deleted the triggers from the automations and re-added them

**Comment by FSHelgeland** [comment]
When I tested my switches I made a test automation so the switch was in a new automation. So maybe there should have been a release note on that?

**Comment by karloygard** [comment]
I *suspect* that this is an unavoidable side effect of fixing the naming issue, but it's regrettable nevertheless. I'll add a notice of the breaking change.
