### ISSUE TITLE
Question: What is the most likely cause of Timeaccount drops?

### ISSUE THREAD

**Issue by alfsolli** [karloygard/xcomfortd-go#63]
I've started to get these in the console a while back
"Timeaccount fell below 10%"

And quickly after "Timeaccount zero, no more transmission possible"
And "TX lost, repeat it, buffer full", at which point sending (for example) dimming messages takes anywhere from 10 to 20 seconds to reach the device. 

I'm guessing it might have to do with memory on the USB stick, but I know way to little about xcomfort to be confident.   Any suggestions are welcome.

**Comment by karloygard** [comment]
This means that you are sending too many messages. The device can only transmit for a relatively short period in an hour, if you send too many messages your time account will be spent and the device will wait before sending more messages. You may have something that's updating light bulbs or similar too often.
