### ISSUE TITLE
Homebridge?

### ISSUE THREAD

**Issue by bakkebo** [karloygard/xcomfortd-go#7]
Hello! Thanks for your amazing work! 
Me myself has an xComfort system set up in my house with all light points with the wireless actuators. 

I am starting my journey to set up all the different smart devices to work through home bridge on a raspberry pi. I wonder, have you got you system to work with homebridge, or do you know anything about this? :) 

I also live in Norway.

**Comment by karloygard** [comment]
I have not experimented with homebridge, only Home Assistant, but I see no reason why it couldn't be made to work. You will likely have to write some code if you want to do that, I'm not familiar with that code, so I cannot say how much work that is.

It's possible to integrate Home Assistant with HomeKit, but you may already be aware of that. I played with it a while ago, and it seemed to work then.
